# Generated by Django 2.2.4 on 2020-07-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
